# Generated by Django 5.2 on 2025-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('full_info', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField()),
                ('link', models.URLField()),
                ('country', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='program_photos/')),
                ('type', models.CharField(max_length=100)),
                ('funding', models.CharField(max_length=100)),
                ('start_age', models.PositiveIntegerField()),
                ('end_age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male🙋🏻\u200d♂️'), ('female', 'Female🙋🏻\u200d♀️'), ('any', 'Any🙋🏻\u200d♂️🙋🏻\u200d♀️')], max_length=10)),
                ('major', models.ManyToManyField(blank=True, to='core.major')),
            ],
        ),
    ]
